[tool.poetry]
name = "gino-stubs"
version = "0.1"
description = "Experimental Gino stubs"
authors = ["Bryan Forbes <bryan@reigndropsfall.net>"]
license = "BSD-3-Clause"

packages = [
	{ include = "gino-stubs" },
	{ include = "ginomypy" }
]
include = [
	"gino-stubs/**/*.pyi",
	"ginomypy/py.typed"
]

[tool.poetry.dependencies]
python = "^3.6"
typing-extensions = ">=3.6.5"
sqlalchemy-stubs = "^0.1"
sqlalchemy = "~1.2.18"

[tool.poetry.dev-dependencies]
attrs = ">=18.0"
black = "^19.3b0"
flake8 = "^3.6"
flake8-bugbear = {version = "^19.3", python = "^3.6"}
flake8-pyi = {version = "^19.2", python = "^3.6"}
lxml = "~4.3.0"
mypy = ">=0.701"
mypy_extensions = ">=0.4.0"
pre-commit = "^1.12"
pytest = "^4.0"
pytest-cov = "^2.6"
pytest-mypy-plugins = "^0.3.0"
pytest-xdist = "^1.24"
py = ">=1.5.2"
gino = ">=0.8.0"

[tool.black]
line-length = 88
target-version = ["py36", "py37"]
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.pytest_cache
  | \.venv
  | external
)/
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
